//EPS.h ClydeSpace EPS telemetry.

//Programmer: Fred Bourbour
//Date:5/25/2014


enum ClydeEPS
{
EPS_GROUND0,
EPS_ARRAY_PLUS_Y_CURRENT,
EPS_ARRAY_PLUS_Y_TEMPERATURE,
EPS_ARRAY_PAIR_Y_VOLTAGE,
EPS_ARRAY_MINUS_X_CURRENT,
EPS_ARRAY_MINUS_X_TEMPERATURE,
EPS_ARRAY_PAIR_X_VOLTAGE,
EPS_ARRAY_PLUS_X_CURRENT,
EPS_ARRAY_PLUS_X_TEMPERATURE,
EPS_ARRAY_PAIR_Z_VOLTAGE,
EPS_ARRAY_PLUS_Z_CURRENT,
EPS_ARRAY_PLUS_Z_TEMPERATURE,
EPS_GROUND1,
EPS_ARRAY_MINUS_Y_CURRENT,
EPS_ARRAY_MINUS_Y_TEMPERATURE,
EPS_GROUND2,
EPS_GROUND3,
EPS_BATTERY_BUS_CURRENT,
EPS_BATTERY1_TEMPERATURE,
EPS_BATTERY1_FULL_VOLTAGE,
EPS_GROUND4,
EPS_BATTERY1_CURRENT_DIRECTION,
EPS_BATTERY1_CURRENT,
EPS_BATTERY0_TEMPERATURE,
EPS_BATTERY0_FULL_VOLTAGE,
EPS_GROUND4,
EPS_5V_CURRENT,
EPS_3PV_CURRENT,
EPS_BATTERY0_CURRENT_DIRECTION,
EPS_BATTERY0_CURRENT,
EPS_ARRAY_MINUS_Z_TEMPERATURE,
EPS_ARRAY_MINUS_Z_CURRENT,

};


uint8_t EPSChannelSelector;
uint8_t EPSChannelData;
